spring.application.name=product-inventory-api

spring.datasource.url= jdbc:postgresql://localhost:5432/practices
spring.datasource.username= postgres
spring.datasource.password= 0000

spring.jpa.hibernate.ddl-auto= update